apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: backendport
  labels:
    name: backend-app
    release: prometheus
  name: backend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - env:
        - name: JAEGER_HOST
          value: simplest-agent.observability.svc.cluster.local
        image: myaxu/metrics-backend-dashboard:latest
        imagePullPolicy: Always
        name: backend-app
        ports:
        - name: backendport
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app
  labels: 
    app: backend-app
spec:
  selector:
    app: backend-app
  ports:
    - name: backendport
      protocol: TCP
      port: 8081
      targetPort: backendport
  type: LoadBalancer

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-app
  namespace: monitoring
  labels:
    app: backend-app
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend-app
  endpoints:
  - port: backendport
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default

    