apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  labels:
    name: frontend-app
    release: prometheus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: myaxu/metrics-myfrontend-dashboard:latest
        imagePullPolicy: Always
        ports:
        - name: frontendport
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  labels:
    app: frontend-app
spec:
  selector:
    app: frontend-app
  ports:
    - name: frontendport
      protocol: TCP
      port: 8080
      targetPort: frontendport
  type: LoadBalancer

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-app
  namespace: monitoring
  labels:
    app: frontend-app
    release: prometheus
spec:
  selector:
    matchLabels:
      app: frontend-app
  endpoints:
  - port: frontendport
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
    