apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial-app
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: trialport
  labels:
    name: trial-app
    release: prometheus  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trial-app
  template:
    metadata:
      labels:
        app: trial-app
    spec:
      containers:
      - name: trial-app
        image: myaxu/trial-app:latest
        imagePullPolicy: Always
        env: 
        - name: JAEGER_HOST
          value: simplest-agent.observability.svc.cluster.local
        ports:
        - name: trialport
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: trial-app
  labels:
    app: trial-app
spec:
  selector:
    app: trial-app
  ports:
    - name: trialport
      protocol: TCP  
      port: 8082
      targetPort: trialport
  type: LoadBalancer


---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trial-app
  namespace: monitoring
  labels:
    app: trial-app
    release: prometheus
spec:
  selector:
    matchLabels:
      app: trial-app
  endpoints:
  - port: trial-app
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
    

